# This file was generated by GoReleaser. DO NOT EDIT.
class Furyagent < Formula
  desc "Fury Agent binary"
  homepage "https://gihub.com/sighupio/furyagent"
  version "0.2.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/sighupio/furyagent/releases/download/v0.2.1/furyagent-darwin-amd64.tar.gz"
    sha256 "98f56e53e73353551a05f7d40996c5a74315b077d32c877be51cc2ceadaff7d1"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/sighupio/furyagent/releases/download/v0.2.1/furyagent-linux-amd64.tar.gz"
      sha256 "64a445dcb718e310c7241d6e3c825399f90ae794f334942802c14abc5028c834"
    end
  end
  
  conflicts_with "furyagent"

  def install
    bin.install 'furyagent'
  end

  test do
    system "#{bin}/furyagent"
  end
end
