# This file was generated by GoReleaser. DO NOT EDIT.
class Furyagent < Formula
  desc "Fury Agent binary"
  homepage "https://gihub.com/sighupio/furyagent"
  version "0.1.3-rc1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/sighupio/furyagent/releases/download/v0.1.3-rc1/furyagent-darwin-amd64.tar.gz"
    sha256 "5e8dbad640b18ad005b42cee9b1a5c11a1d7a60eef4b8f5e830e36512db3c408"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/sighupio/furyagent/releases/download/v0.1.3-rc1/furyagent-linux-amd64.tar.gz"
      sha256 "1eb8c55c1dfa4c5bd1f7def021e8c4e0fcf44f4275eade1a3d5976b5a011d3f0"
    end
  end
  
  conflicts_with "furyagent"

  def install
    bin.install 'furyagent'
  end

  test do
    system "#{bin}/furyagent"
  end
end
